// CPP L:\smali2cpp20\x64\Release\out\android\icu\text\RBBIRuleParseTable.smali
#include "java2ctype.h"
#include "android.icu.text.RBBIRuleParseTable_S_RBBIRuleTableElement.h"
#include "android.icu.text.RBBIRuleParseTable.h"
#include "java.lang.String.h"

static android::icu::text::RBBIRuleParseTable::doCheckVarDef = 0x1s;
static android::icu::text::RBBIRuleParseTable::doDotAny = 0x2s;
static android::icu::text::RBBIRuleParseTable::doEndAssign = 0x3s;
static android::icu::text::RBBIRuleParseTable::doEndOfRule = 0x4s;
static android::icu::text::RBBIRuleParseTable::doEndVariableName = 0x5s;
static android::icu::text::RBBIRuleParseTable::doExit = 0x6s;
static android::icu::text::RBBIRuleParseTable::doExprCatOperator = 0x7s;
static android::icu::text::RBBIRuleParseTable::doExprFinished = 0x8s;
static android::icu::text::RBBIRuleParseTable::doExprOrOperator = 0x9s;
static android::icu::text::RBBIRuleParseTable::doExprRParen = 0xas;
static android::icu::text::RBBIRuleParseTable::doExprStart = 0xbs;
static android::icu::text::RBBIRuleParseTable::doLParen = 0xcs;
static android::icu::text::RBBIRuleParseTable::doNOP = 0xds;
static android::icu::text::RBBIRuleParseTable::doNoChain = 0xes;
static android::icu::text::RBBIRuleParseTable::doOptionEnd = 0xfs;
static android::icu::text::RBBIRuleParseTable::doOptionStart = 0x10s;
static android::icu::text::RBBIRuleParseTable::doReverseDir = 0x11s;
static android::icu::text::RBBIRuleParseTable::doRuleChar = 0x12s;
static android::icu::text::RBBIRuleParseTable::doRuleError = 0x13s;
static android::icu::text::RBBIRuleParseTable::doRuleErrorAssignExpr = 0x14s;
static android::icu::text::RBBIRuleParseTable::doScanUnicodeSet = 0x15s;
static android::icu::text::RBBIRuleParseTable::doSlash = 0x16s;
static android::icu::text::RBBIRuleParseTable::doStartAssign = 0x17s;
static android::icu::text::RBBIRuleParseTable::doStartTagValue = 0x18s;
static android::icu::text::RBBIRuleParseTable::doStartVariableName = 0x19s;
static android::icu::text::RBBIRuleParseTable::doTagDigit = 0x1as;
static android::icu::text::RBBIRuleParseTable::doTagExpectedError = 0x1bs;
static android::icu::text::RBBIRuleParseTable::doTagValue = 0x1cs;
static android::icu::text::RBBIRuleParseTable::doUnaryOpPlus = 0x1ds;
static android::icu::text::RBBIRuleParseTable::doUnaryOpQuestion = 0x1es;
static android::icu::text::RBBIRuleParseTable::doUnaryOpStar = 0x1fs;
static android::icu::text::RBBIRuleParseTable::doVariableNameExpectedErr = 0x20s;
static android::icu::text::RBBIRuleParseTable::gRuleParseStateTable = nullptr;
static android::icu::text::RBBIRuleParseTable::kRuleSet_default = 0xffs;
static android::icu::text::RBBIRuleParseTable::kRuleSet_digit_char = 0x80s;
static android::icu::text::RBBIRuleParseTable::kRuleSet_eof = 0xfcs;
static android::icu::text::RBBIRuleParseTable::kRuleSet_escaped = 0xfes;
static android::icu::text::RBBIRuleParseTable::kRuleSet_name_char = 0x81s;
static android::icu::text::RBBIRuleParseTable::kRuleSet_name_start_char = 0x82s;
static android::icu::text::RBBIRuleParseTable::kRuleSet_rule_char = 0x83s;
static android::icu::text::RBBIRuleParseTable::kRuleSet_white_space = 0x84s;
// .method static constructor <clinit>()V
void android::icu::text::RBBIRuleParseTable::static_cinit()
{
	
	short cVar0;
	int cVar1;
	bool cVar2;
	std::shared_ptr<java::lang::String> cVar3;
	int cVar4;
	std::shared<std::vector<std::vector<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>>> cVar5;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar6;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar7;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar8;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar9;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar10;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar11;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar12;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar13;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar14;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar15;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar16;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar17;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar18;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar19;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar20;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar21;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar22;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar23;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar24;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar25;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar26;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar27;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar28;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar29;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar30;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar31;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar32;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar33;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar34;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar35;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar36;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar37;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar38;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar39;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar40;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar41;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar42;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar43;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar44;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar45;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar46;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar47;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar48;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar49;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar50;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar51;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar52;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar53;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar54;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar55;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar56;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar57;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar58;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar59;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar60;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar61;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar62;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar63;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar64;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar65;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar66;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar67;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar68;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar69;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar70;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar71;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar72;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar73;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar74;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar75;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar76;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar77;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar78;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar79;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar80;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar81;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar82;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar83;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar84;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar85;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar86;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar87;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar88;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar89;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar90;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar91;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar92;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar93;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar94;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar95;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar96;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar97;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar98;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar99;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar100;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar101;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar102;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar103;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar104;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar105;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar106;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar107;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar108;
	std::shared_ptr<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement> cVar109;
	
	cVar0 = 0xd;
	cVar1 = 0xff;
	cVar2 = 0x1;
	cVar3 = 0x0;
	cVar4 = 0x0;
	cVar5 = std::make_shared<std::vector<std::vector<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>>>(0x68);
	cVar6 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, cVar4, cVar4, cVar4, cVar2, cVar3);
	cVar5[cVar4] = cVar6;
	cVar7 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, 0xfe, 0x1d, 0x9, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("start")));
	cVar5[cVar2] = cVar7;
	cVar8 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, cVar2, cVar4, cVar2, cVar3);
	cVar5[0x2] = cVar8;
	cVar9 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xe, 0x5e, 0xc, 0x9, cVar2, cVar3);
	cVar5[0x3] = cVar9;
	cVar10 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, 0x24, 0x58, 0x62, cVar4, cVar3);
	cVar5[0x4] = cVar10;
	cVar11 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x21, 0x13, cVar4, cVar2, cVar3);
	cVar5[0x5] = cVar11;
	cVar12 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x3b, cVar2, cVar4, cVar2, cVar3);
	cVar5[0x6] = cVar12;
	cVar13 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0xfc, cVar4, cVar4, cVar4, cVar3);
	cVar5[0x7] = cVar13;
	cVar14 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, cVar1, 0x1d, 0x9, cVar4, cVar3);
	cVar5[0x8] = cVar14;
	cVar15 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x4, 0x3b, cVar2, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("break-rule-end")));
	cVar5[0x9] = cVar15;
	cVar16 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x9, cVar4, cVar2, cVar3);
	cVar5[0xa] = cVar16;
	cVar17 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0xb] = cVar17;
	cVar18 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, 0xfe, 0x1d, cVar4, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("start-after-caret")));
	cVar5[0xc] = cVar18;
	cVar19 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0xc, cVar4, cVar2, cVar3);
	cVar5[cVar0] = cVar19;
	cVar20 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, 0x5e, 0x67, cVar4, cVar4, cVar3);
	cVar5[0xe] = cVar20;
	cVar21 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, 0x24, 0x58, 0x25, cVar4, cVar3);
	cVar5[0xf] = cVar21;
	cVar22 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, 0x3b, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x10] = cVar22;
	cVar23 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, 0xfc, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x11] = cVar23;
	cVar24 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, cVar1, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x12] = cVar24;
	cVar25 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x21, 0x15, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("rev-option")));
	cVar5[0x13] = cVar25;
	cVar26 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x11, cVar1, 0x1c, 0x9, cVar4, cVar3);
	cVar5[0x14] = cVar26;
	cVar27 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x10, 0x82, 0x17, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("option-scan1")));
	cVar5[0x15] = cVar27;
	cVar28 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x16] = cVar28;
	cVar29 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x81, 0x17, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("option-scan2")));
	cVar5[0x17] = cVar29;
	cVar30 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xf, cVar1, 0x19, cVar4, cVar4, cVar3);
	cVar5[0x18] = cVar30;
	cVar31 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x3b, cVar2, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("option-scan3")));
	cVar5[0x19] = cVar31;
	cVar32 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x19, cVar4, cVar2, cVar3);
	cVar5[0x1a] = cVar32;
	cVar33 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x1b] = cVar33;
	cVar34 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xb, cVar1, 0x1d, 0x9, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("reverse-rule")));
	cVar5[0x1c] = cVar34;
	cVar35 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x12, 0xfe, 0x26, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("term")));
	cVar5[0x1d] = cVar35;
	cVar36 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x1d, cVar4, cVar2, cVar3);
	cVar5[0x1e] = cVar36;
	cVar37 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x12, 0x83, 0x26, cVar4, cVar2, cVar3);
	cVar5[0x1f] = cVar37;
	cVar38 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x5b, 0x5e, 0x26, cVar4, cVar3);
	cVar5[0x20] = cVar38;
	cVar39 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xc, 0x28, 0x1d, 0x26, cVar2, cVar3);
	cVar5[0x21] = cVar39;
	cVar40 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x24, 0x58, 0x25, cVar4, cVar3);
	cVar5[0x22] = cVar40;
	cVar41 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x2, 0x2e, 0x26, cVar4, cVar2, cVar3);
	cVar5[0x23] = cVar41;
	cVar42 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x13, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x24] = cVar42;
	cVar43 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar2, cVar1, 0x26, cVar4, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("term-var-ref")));
	cVar5[0x25] = cVar43;
	cVar44 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x26, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("expr-mod")));
	cVar5[0x26] = cVar44;
	cVar45 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1f, 0x2a, 0x2b, cVar4, cVar2, cVar3);
	cVar5[0x27] = cVar45;
	cVar46 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1d, 0x2b, 0x2b, cVar4, cVar2, cVar3);
	cVar5[0x28] = cVar46;
	cVar47 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1e, 0x3f, 0x2b, cVar4, cVar2, cVar3);
	cVar5[0x29] = cVar47;
	cVar48 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, cVar1, 0x2b, cVar4, cVar4, cVar3);
	cVar5[0x2a] = cVar48;
	cVar49 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0xfe, 0x1d, cVar4, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("expr-cont")));
	cVar5[0x2b] = cVar49;
	cVar50 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x2b, cVar4, cVar2, cVar3);
	cVar5[0x2c] = cVar50;
	cVar51 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x83, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x2d] = cVar51;
	cVar52 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x5b, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x2e] = cVar52;
	cVar53 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x28, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x2f] = cVar53;
	cVar54 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x24, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x30] = cVar54;
	cVar55 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x2e, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x31] = cVar55;
	cVar56 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x2f, 0x37, cVar4, cVar4, cVar3);
	cVar5[0x32] = cVar56;
	cVar57 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x7b, 0x43, cVar4, cVar2, cVar3);
	cVar5[0x33] = cVar57;
	cVar58 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x9, 0x7c, 0x1d, cVar4, cVar2, cVar3);
	cVar5[0x34] = cVar58;
	cVar59 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xa, 0x29, cVar1, cVar4, cVar2, cVar3);
	cVar5[0x35] = cVar59;
	cVar60 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x8, cVar1, cVar1, cVar4, cVar4, cVar3);
	cVar5[0x36] = cVar60;
	cVar61 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x16, 0x2f, 0x39, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("look-ahead")));
	cVar5[0x37] = cVar61;
	cVar62 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x38] = cVar62;
	cVar63 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0xfe, 0x1d, cVar4, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("expr-cont-no-slash")));
	cVar5[0x39] = cVar63;
	cVar64 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x2b, cVar4, cVar2, cVar3);
	cVar5[0x3a] = cVar64;
	cVar65 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x83, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x3b] = cVar65;
	cVar66 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x5b, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x3c] = cVar66;
	cVar67 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x28, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x3d] = cVar67;
	cVar68 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x24, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x3e] = cVar68;
	cVar69 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x2e, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x3f] = cVar69;
	cVar70 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x9, 0x7c, 0x1d, cVar4, cVar2, cVar3);
	cVar5[0x40] = cVar70;
	cVar71 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xa, 0x29, cVar1, cVar4, cVar2, cVar3);
	cVar5[0x41] = cVar71;
	cVar72 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x8, cVar1, cVar1, cVar4, cVar4, cVar3);
	cVar5[0x42] = cVar72;
	cVar73 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x43, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("tag-open")));
	cVar5[0x43] = cVar73;
	cVar74 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x18, 0x80, 0x46, cVar4, cVar4, cVar3);
	cVar5[0x44] = cVar74;
	cVar75 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1b, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x45] = cVar75;
	cVar76 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x4a, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("tag-value")));
	cVar5[0x46] = cVar76;
	cVar77 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x7d, 0x4a, cVar4, cVar4, cVar3);
	cVar5[0x47] = cVar77;
	cVar78 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1a, 0x80, 0x46, cVar4, cVar2, cVar3);
	cVar5[0x48] = cVar78;
	cVar79 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1b, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x49] = cVar79;
	cVar80 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x4a, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("tag-close")));
	cVar5[0x4a] = cVar80;
	cVar81 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1c, 0x7d, 0x4d, cVar4, cVar2, cVar3);
	cVar5[0x4b] = cVar81;
	cVar82 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x1b, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x4c] = cVar82;
	cVar83 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0xfe, 0x1d, cVar4, cVar4, std::make_shared<java::lang::String>(std::make_shared<char[]>("expr-cont-no-tag")));
	cVar5[0x4d] = cVar83;
	cVar84 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x4d, cVar4, cVar2, cVar3);
	cVar5[0x4e] = cVar84;
	cVar85 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x83, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x4f] = cVar85;
	cVar86 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x5b, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x50] = cVar86;
	cVar87 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x28, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x51] = cVar87;
	cVar88 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x24, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x52] = cVar88;
	cVar89 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x2e, 0x1d, cVar4, cVar4, cVar3);
	cVar5[0x53] = cVar89;
	cVar90 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x7, 0x2f, 0x37, cVar4, cVar4, cVar3);
	cVar5[0x54] = cVar90;
	cVar91 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x9, 0x7c, 0x1d, cVar4, cVar2, cVar3);
	cVar5[0x55] = cVar91;
	cVar92 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0xa, 0x29, cVar1, cVar4, cVar2, cVar3);
	cVar5[0x56] = cVar92;
	cVar93 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x8, cVar1, cVar1, cVar4, cVar4, cVar3);
	cVar5[0x57] = cVar93;
	cVar94 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x19, 0x24, 0x5a, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("scan-var-name")));
	cVar5[0x58] = cVar94;
	cVar95 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x59] = cVar95;
	cVar96 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x82, 0x5c, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("scan-var-start")));
	cVar5[0x5a] = cVar96;
	cVar97 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x20, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x5b] = cVar97;
	cVar98 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x81, 0x5c, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("scan-var-body")));
	cVar5[0x5c] = cVar98;
	cVar99 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x5, cVar1, cVar1, cVar4, cVar4, cVar3);
	cVar5[0x5d] = cVar99;
	cVar100 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x15, 0x5b, cVar1, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("scan-unicode-set")));
	cVar5[0x5e] = cVar100;
	cVar101 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x15, 0x70, cVar1, cVar4, cVar2, cVar3);
	cVar5[0x5f] = cVar101;
	cVar102 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x15, 0x50, cVar1, cVar4, cVar2, cVar3);
	cVar5[0x60] = cVar102;
	cVar103 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x61] = cVar103;
	cVar104 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, 0x84, 0x62, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("assign-or-rule")));
	cVar5[0x62] = cVar104;
	cVar105 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x17, 0x3d, 0x1d, 0x65, cVar2, cVar3);
	cVar5[0x63] = cVar105;
	cVar106 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(cVar0, cVar1, 0x25, 0x9, cVar4, cVar3);
	cVar5[0x64] = cVar106;
	cVar107 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x3, 0x3b, cVar2, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("assign-end")));
	cVar5[0x65] = cVar107;
	cVar108 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x14, cVar1, 0x67, cVar4, cVar4, cVar3);
	cVar5[0x66] = cVar108;
	cVar109 = std::make_shared<android::icu::text::RBBIRuleParseTable_S_RBBIRuleTableElement>(0x6, cVar1, 0x67, cVar4, cVar2, std::make_shared<java::lang::String>(std::make_shared<char[]>("errorDeath")));
	cVar5[0x67] = cVar109;
	android::icu::text::RBBIRuleParseTable::gRuleParseStateTable = cVar5;
	return;

}
// .method constructor <init>()V
android::icu::text::RBBIRuleParseTable::RBBIRuleParseTable()
{
	
	// 2300    invoke-direct {p0}, Ljava/lang/Object;-><init>()V
	return;

}


