// CPP L:\smali2cpp20\x64\Release\out\sun\security\util\Resources.smali
#include "java2ctype.h"
#include "java.lang.Object.h"
#include "java.lang.String.h"
#include "sun.security.util.Resources.h"

static sun::security::util::Resources::contents;
// .method static constructor <clinit>()V
void sun::security::util::Resources::static_cinit()
{
	
	int cVar0;
	int cVar1;
	int cVar2;
	std::shared<std::vector<std::vector<std::vector<java::lang::Object>>>> cVar3;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar4;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar5;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar6;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar7;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar8;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar9;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar10;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar11;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar12;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar13;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar14;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar15;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar16;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar17;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar18;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar19;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar20;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar21;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar22;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar23;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar24;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar25;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar26;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar27;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar28;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar29;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar30;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar31;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar32;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar33;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar34;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar35;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar36;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar37;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar38;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar39;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar40;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar41;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar42;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar43;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar44;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar45;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar46;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar47;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar48;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar49;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar50;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar51;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar52;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar53;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar54;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar55;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar56;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar57;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar58;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar59;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar60;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar61;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar62;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar63;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar64;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar65;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar66;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar67;
	std::shared<std::vector<std::vector<java::lang::Object>>> cVar68;
	
	cVar0 = 0x2;
	cVar1 = 0x1;
	cVar2 = 0x0;
	cVar3 = std::make_shared<std::vector<std::vector<std::vector<java::lang::Object>>>>(0x41);
	cVar4 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar4[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid.null.input.s."));
	cVar4[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid null input(s)"));
	cVar3[cVar2] = cVar4;
	cVar5 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar5[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("actions.can.only.be.read."));
	cVar5[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("actions can only be \'read\'"));
	cVar3[cVar1] = cVar5;
	cVar6 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar6[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("permission.name.name.syntax.invalid."));
	cVar6[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("permission name [{0}] syntax invalid: "));
	cVar3[cVar0] = cVar6;
	cVar7 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar7[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Credential.Class.not.followed.by.a.Principal.Class.and.Name"));
	cVar7[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Credential Class not followed by a Principal Class and Name"));
	cVar3[0x3] = cVar7;
	cVar8 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar8[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Principal.Class.not.followed.by.a.Principal.Name"));
	cVar8[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Principal Class not followed by a Principal Name"));
	cVar3[0x4] = cVar8;
	cVar9 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar9[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Principal.Name.must.be.surrounded.by.quotes"));
	cVar9[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Principal Name must be surrounded by quotes"));
	cVar3[0x5] = cVar9;
	cVar10 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar10[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Principal.Name.missing.end.quote"));
	cVar10[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Principal Name missing end quote"));
	cVar3[0x6] = cVar10;
	cVar11 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar11[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("PrivateCredentialPermission.Principal.Class.can.not.be.a.wildcard.value.if.Principal.Name.is.not.a.wildcard.value"));
	cVar11[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("PrivateCredentialPermission Principal Class can not be a wildcard (*) value if Principal Name is not a wildcard (*) value"));
	cVar3[0x7] = cVar11;
	cVar12 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar12[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("CredOwner.Principal.Class.class.Principal.Name.name"));
	cVar12[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("CredOwner:\n\tPrincipal Class = {0}\n\tPrincipal Name = {1}"));
	cVar3[0x8] = cVar12;
	cVar13 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar13[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("provided.null.name"));
	cVar13[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("provided null name"));
	cVar3[0x9] = cVar13;
	cVar14 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar14[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("provided.null.keyword.map"));
	cVar14[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("provided null keyword map"));
	cVar3[0xa] = cVar14;
	cVar15 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar15[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("provided.null.OID.map"));
	cVar15[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("provided null OID map"));
	cVar3[0xb] = cVar15;
	cVar16 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar16[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("NEWLINE"));
	cVar16[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("\n"));
	cVar3[0xc] = cVar16;
	cVar17 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar17[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid.null.AccessControlContext.provided"));
	cVar17[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid null AccessControlContext provided"));
	cVar3[0xd] = cVar17;
	cVar18 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar18[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid.null.action.provided"));
	cVar18[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid null action provided"));
	cVar3[0xe] = cVar18;
	cVar19 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar19[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid.null.Class.provided"));
	cVar19[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid null Class provided"));
	cVar3[0xf] = cVar19;
	cVar20 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar20[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Subject."));
	cVar20[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Subject:\n"));
	cVar3[0x10] = cVar20;
	cVar21 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar21[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>(".Principal."));
	cVar21[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("\tPrincipal: "));
	cVar3[0x11] = cVar21;
	cVar22 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar22[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>(".Public.Credential."));
	cVar22[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("\tPublic Credential: "));
	cVar3[0x12] = cVar22;
	cVar23 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar23[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>(".Private.Credentials.inaccessible."));
	cVar23[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("\tPrivate Credentials inaccessible\n"));
	cVar3[0x13] = cVar23;
	cVar24 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar24[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>(".Private.Credential."));
	cVar24[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("\tPrivate Credential: "));
	cVar3[0x14] = cVar24;
	cVar25 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar25[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>(".Private.Credential.inaccessible."));
	cVar25[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("\tPrivate Credential inaccessible\n"));
	cVar3[0x15] = cVar25;
	cVar26 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar26[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Subject.is.read.only"));
	cVar26[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Subject is read-only"));
	cVar3[0x16] = cVar26;
	cVar27 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar27[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("attempting.to.add.an.object.which.is.not.an.instance.of.java.security.Principal.to.a.Subject.s.Principal.Set"));
	cVar27[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("attempting to add an object which is not an instance of java.security.Principal to a Subject\'s Principal Set"));
	cVar3[0x17] = cVar27;
	cVar28 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar28[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("attempting.to.add.an.object.which.is.not.an.instance.of.class"));
	cVar28[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("attempting to add an object which is not an instance of {0}"));
	cVar3[0x18] = cVar28;
	cVar29 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar29[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("LoginModuleControlFlag."));
	cVar29[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("LoginModuleControlFlag: "));
	cVar3[0x19] = cVar29;
	cVar30 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar30[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Invalid.null.input.name"));
	cVar30[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Invalid null input: name"));
	cVar3[0x1a] = cVar30;
	cVar31 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar31[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("No.LoginModules.configured.for.name"));
	cVar31[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("No LoginModules configured for {0}"));
	cVar3[0x1b] = cVar31;
	cVar32 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar32[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid.null.Subject.provided"));
	cVar32[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid null Subject provided"));
	cVar3[0x1c] = cVar32;
	cVar33 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar33[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid.null.CallbackHandler.provided"));
	cVar33[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("invalid null CallbackHandler provided"));
	cVar3[0x1d] = cVar33;
	cVar34 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar34[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("null.subject.logout.called.before.login"));
	cVar34[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("null subject - logout called before login"));
	cVar3[0x1e] = cVar34;
	cVar35 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar35[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.instantiate.LoginModule.module.because.it.does.not.provide.a.no.argument.constructor"));
	cVar35[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to instantiate LoginModule, {0}, because it does not provide a no-argument constructor"));
	cVar3[0x1f] = cVar35;
	cVar36 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar36[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.instantiate.LoginModule"));
	cVar36[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to instantiate LoginModule"));
	cVar3[0x20] = cVar36;
	cVar37 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar37[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.instantiate.LoginModule."));
	cVar37[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to instantiate LoginModule: "));
	cVar3[0x21] = cVar37;
	cVar38 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar38[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.find.LoginModule.class."));
	cVar38[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to find LoginModule class: "));
	cVar3[0x22] = cVar38;
	cVar39 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar39[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.access.LoginModule."));
	cVar39[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to access LoginModule: "));
	cVar3[0x23] = cVar39;
	cVar40 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar40[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Login.Failure.all.modules.ignored"));
	cVar40[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("Login Failure: all modules ignored"));
	cVar3[0x24] = cVar40;
	cVar41 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar41[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("java.security.policy.error.parsing.policy.message"));
	cVar41[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("java.security.policy: error parsing {0}:\n\t{1}"));
	cVar3[0x25] = cVar41;
	cVar42 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar42[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("java.security.policy.error.adding.Permission.perm.message"));
	cVar42[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("java.security.policy: error adding Permission, {0}:\n\t{1}"));
	cVar3[0x26] = cVar42;
	cVar43 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar43[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("java.security.policy.error.adding.Entry.message"));
	cVar43[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("java.security.policy: error adding Entry:\n\t{0}"));
	cVar3[0x27] = cVar43;
	cVar44 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar44[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("alias.name.not.provided.pe.name."));
	cVar44[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("alias name not provided ({0})"));
	cVar3[0x28] = cVar44;
	cVar45 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar45[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.perform.substitution.on.alias.suffix"));
	cVar45[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to perform substitution on alias, {0}"));
	cVar3[0x29] = cVar45;
	cVar46 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar46[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("substitution.value.prefix.unsupported"));
	cVar46[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("substitution value, {0}, unsupported"));
	cVar3[0x2a] = cVar46;
	cVar47 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar47[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("LPARAM"));
	cVar47[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("("));
	cVar3[0x2b] = cVar47;
	cVar48 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar48[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("RPARAM"));
	cVar48[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>(")"));
	cVar3[0x2c] = cVar48;
	cVar49 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar49[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("type.can.t.be.null"));
	cVar49[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("type can\'t be null"));
	cVar3[0x2d] = cVar49;
	cVar50 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar50[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("keystorePasswordURL.can.not.be.specified.without.also.specifying.keystore"));
	cVar50[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("keystorePasswordURL can not be specified without also specifying keystore"));
	cVar3[0x2e] = cVar50;
	cVar51 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar51[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected.keystore.type"));
	cVar51[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected keystore type"));
	cVar3[0x2f] = cVar51;
	cVar52 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar52[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected.keystore.provider"));
	cVar52[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected keystore provider"));
	cVar3[0x30] = cVar52;
	cVar53 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar53[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("multiple.Codebase.expressions"));
	cVar53[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("multiple Codebase expressions"));
	cVar3[0x31] = cVar53;
	cVar54 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar54[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("multiple.SignedBy.expressions"));
	cVar54[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("multiple SignedBy expressions"));
	cVar3[0x32] = cVar54;
	cVar55 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar55[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("duplicate.keystore.domain.name"));
	cVar55[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("duplicate keystore domain name: {0}"));
	cVar3[0x33] = cVar55;
	cVar56 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar56[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("duplicate.keystore.name"));
	cVar56[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("duplicate keystore name: {0}"));
	cVar3[0x34] = cVar56;
	cVar57 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar57[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("SignedBy.has.empty.alias"));
	cVar57[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("SignedBy has empty alias"));
	cVar3[0x35] = cVar57;
	cVar58 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar58[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name"));
	cVar58[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("can not specify Principal with a wildcard class without a wildcard name"));
	cVar3[0x36] = cVar58;
	cVar59 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar59[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected.codeBase.or.SignedBy.or.Principal"));
	cVar59[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected codeBase or SignedBy or Principal"));
	cVar3[0x37] = cVar59;
	cVar60 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar60[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected.permission.entry"));
	cVar60[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected permission entry"));
	cVar3[0x38] = cVar60;
	cVar61 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar61[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("number."));
	cVar61[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("number "));
	cVar3[0x39] = cVar61;
	cVar62 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar62[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected.expect.read.end.of.file."));
	cVar62[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected [{0}], read [end of file]"));
	cVar3[0x3a] = cVar62;
	cVar63 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar63[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected.read.end.of.file."));
	cVar63[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("expected [;], read [end of file]"));
	cVar3[0x3b] = cVar63;
	cVar64 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar64[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("line.number.msg"));
	cVar64[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("line {0}: {1}"));
	cVar3[0x3c] = cVar64;
	cVar65 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar65[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("line.number.expected.expect.found.actual."));
	cVar65[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("line {0}: expected [{1}], found [{2}]"));
	cVar3[0x3d] = cVar65;
	cVar66 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar66[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("null.principalClass.or.principalName"));
	cVar66[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("null principalClass or principalName"));
	cVar3[0x3e] = cVar66;
	cVar67 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar67[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("PKCS11.Token.providerName.Password."));
	cVar67[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("PKCS11 Token [{0}] Password: "));
	cVar3[0x3f] = cVar67;
	cVar68 = std::make_shared<std::vector<std::vector<java::lang::Object>>>(cVar0);
	cVar68[cVar2] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable.to.instantiate.Subject.based.policy"));
	cVar68[cVar1] = std::make_shared<java::lang::String>(std::make_shared<char[]>("unable to instantiate Subject-based policy"));
	cVar3[0x40] = cVar68;
	sun::security::util::Resources::contents = cVar3;
	return;

}
// .method public constructor <init>()V
sun::security::util::Resources::Resources()
{
	
	// 1079    invoke-direct {p0}, Ljava/util/ListResourceBundle;-><init>()V
	return;

}
// .method public getContents()[[Ljava/lang/Object;
std::shared_ptr<java::lang::Object> sun::security::util::Resources::getContents()
{
	
	return sun::security::util::Resources::contents;

}


